### ISSUE TITLE
Windows compilation (CMake) 

### ISSUE THREAD

**Issue by purell** [LibVNC/libvncserver#117]
Hi, 

I would like to build libvncserver for Windows. Here is what I have tried :
- Opening de CMakeLists.txt with GUI Cmake. 
- Once Cmake try configuring I'm getting warning about many library not found as (Openssl, zlib, pthread, etc....) 

I have many question :
- Is cmake relay supported and to suppose to work ? Is somebody here succeed? 
- I imagine I need to download et build separately those missing library before configuring the project? If yes then I tried to build openssl but when returning to Cmake GUI it seems that some configuration variable are missing.  Do I need to copy paste from "rfb/rfbconfig.h.cmake" and configure properly those variables?

I hope getting help after that I will do my best to produce a guide to help other like me. 

Best regards

**Comment by AhmedDeif** [comment]
I am also trying to build using CMake but did `not` succeed yet.
Did you add the OpenSSl environment variables ? 
Those include:
1. OPENSSL_ROOT_DIR
2. OPENSSL_LIBRARIES
3. OPENSSL_INCLUDE_DIR

`CMake Error at C:/_development/software/share/cmake-3.5/Modules/TestBigEndian.cmake:51 (message):
Call Stack (most recent call first):
  CMakeLists.txt:164 (TEST_BIG_ENDIAN)`

**Comment by jiulongw** [comment]
TestBigEndian failed because it cannot compile test code that checks for endian (see couple of errors above this error).  If you look at cmake error log, you will see details.  The root cause is one of the cpp flags (-W) is not compatible with cl.exe.

You can simply remove -W from CPPFLAGS in `CMakeLists.txt`.  That will fix the endian tests.

However there are other errors which made me eventually give up cmake and use msys2 instead...

**Comment by bk138** [comment]
Pls see https://github.com/LibVNC/libvncserver/blob/master/.appveyor.yml which works and feel free to re-open if you have questions.
