### ISSUE TITLE
Difference between GotFrameBufferUpdate and FinishedFrameBufferUpdate

### ISSUE THREAD

**Issue by carlonluca** [LibVNC/libvncserver#292]
Hello! Can someone explain the difference between these two? The examples seem to use the former, but I had a few issues with KRDC, which I wasn't having with other clients. It seemed like when large areas were changing (like watching a fullscreen video), there were many small changes from the top to the bottom. The effect was bad on slow devices.
I replaced GotFrameBufferUpdate with FinishedFrameBufferUpdate and the issue disappeared or improved.
Can someone provide a bit more info about the difference, so that I can try to understand if I should propose the patch to KRDC? Thanks! (btw, I would also place KRDC in the list in the readme :-) )

**Comment by i-shcheglakov** [comment]
I believe it might be due to the fact that `FinishedFrameBufferUpdate()` is invoked after `SendIncrementalFramebufferUpdateRequest()`. See `https://github.com/LibVNC/libvncserver/blob/master/libvncclient/rfbproto.c` line 2203. So while your client processes updated frame in the meantime the server prepares a new one to be sent. In case of `GotFrameBufferUpdate()` you process updated frame first and the new one requested afterwards. It may give some performance boost, I guess.

**Comment by bk138** [comment]
One https://github.com/rfbproto/rfbproto/blob/master/rfbproto.rst#framebufferupdate by the server can contain multiple rectangular updates. `GotFrameBufferUpdate()` handles those rects whereas `FinishedFrameBufferUpdate()` indicates the complete processing of all rects of a single framebuffer update sent by the server.
