### ISSUE TITLE
hybiReadHeader reads past websocket header

### ISSUE THREAD

**Issue by monitor6** [LibVNC/libvncserver#297]
Hi, 

I encountered a problem with direct websocket connections between noVNC and x11vnc, the same as described here: https://github.com/novnc/noVNC/issues/874

In my understanding this is a bug with ws_decode.c: `hybiReadHeader()` always tries to read 14 bytes, but the header can be as short as 6 bytes. The bug happens when the payload of the websocket frame is shorter than 8 bytes and the next frame is already available to be read from the socket (e.g. noVNC sending 6-byte pointerEvents in quick succession). Then `hybiReadHeader()` reads past the payload, `hybiRemaining()` blows up due to wraparound, and the header of the next websocket frame is interpreted as being RFB protocol, leading to "unknown message type" errors.

The fix might be pretty simple, like just read `WS_HYBI_HEADER_LEN_SHORT` initially, instead of `WSHLENMAX`. However I'm not so sure if this is really all there is to it. Also, it seems rather difficult to write tests cases for these kind of issues..

**Comment by Lightwars** [comment]
I have seen the disconnecting effect of noVNC while using the example server on my linux machine.
Trying the fix given above resolved it and the connection was stable.

**Comment by bk138** [comment]
@kanaka kindly requesting to share your thoughts on this, time permitting :-)

**Comment by bk138** [comment]
> I have seen the disconnecting effect of noVNC while using the example server on my linux machine.
> Trying the fix given above resolved it and the connection was stable.

Do you have a PR at hand?

**Comment by Lightwars** [comment]
@bk138 I can do one tomorrow.

**Comment by kanaka** [comment]
@bk138 that does sound like a bug parsing the header since the spec defines the payload length as a variable length field that can be either 7 bits, 7+16 bits, or 7+64 bits (https://tools.ietf.org/html/rfc6455#section-5). I don't see anything wrong with the code that parses the payload length: https://github.com/LibVNC/libvncserver/blob/master/libvncserver/ws_decode.c#L219. And the header lengths look right: https://github.com/LibVNC/libvncserver/blob/161e7cab026dd89dacd85208b74834cc4c509f72/libvncserver/ws_decode.c#L8 but I've only had time to give it a very quick look.

**Comment by bk138** [comment]
Closed by #301
