### ISSUE TITLE
How to compile simplest example

### ISSUE THREAD

**Issue by andrey-sitsko** [LibVNC/libvncserver#76]
Hi!
My knowledge in Ubuntu is pretty scarce and it's difficult for me to deal with VNC libraries and compile my program. I build LibVNCServer using ./autogen.sh and doesn't know what to do next. Can you explain me step by step what should I do to compile anything, using your library.
Thanks for your help!

**Comment by cinemast** [comment]
LibVNCServer is already available in Ubuntu using:

```sh
sudo apt-get install libvncserver-dev
```

If you need the latest version you can build it using the following commands:
```sh
sudo apt-get install build-essential libgnutls28-dev libjpeg-dev libgcrypt20-dev zlib1g-dev
./autogen.sh
./configure
make
sudo make install
```

**Comment by andrey-sitsko** [comment]
Thank you a lot, it's really save me a lot of time!

**Comment by andrey-sitsko** [comment]
Hi again, I have another problem now(((
I wanna to compile simple server example:

#include <rfb/rfb.h>

int main(int argc,char** argv)
{
  rfbScreenInfoPtr server=rfbGetScreen(&argc,argv,400,300,8,3,4);
  server->frameBuffer=malloc(400*300*4);
  rfbInitServer(server);
  rfbRunEventLoop(server,-1,FALSE);
  return(0);
}

But have next output:
/tmp/ccu8UC6X.o: In function `main':
undefined reference to `rfbGetScreen'
undefined reference to `rfbInitServerWithPthreadsAndZRLE'
undefined reference to `rfbRunEventLoop'

Compiler find libraries, but get stuck on function reference, what I do wrong?
P.S. I do everything you advice me to do to install libraries.

**Comment by andrey-sitsko** [comment]
Hi again, I have another problem now(((
I wanna to compile simple server example:
```
#include
int main(int argc,char** argv)
{
rfbScreenInfoPtr server=rfbGetScreen(&argc,argv,400,300,8,3,4);
server->frameBuffer=malloc(4003004);
rfbInitServer(server);
rfbRunEventLoop(server,-1,FALSE);
return(0);
}
```
But have next output:
```
/tmp/ccu8UC6X.o: In function main': 
undefined reference torfbGetScreen'
undefined reference to rfbInitServerWithPthreadsAndZRLE' 
undefined reference torfbRunEventLoop'
```

Compiler find libraries, but get stuck on function reference, what I do wrong?
P.S. I do everything you advice me to do to install libraries.

**Comment by cinemast** [comment]
Hi andrey!

I really think you should get more familiar with C programming especially linking, before you start using libvncserver. The errors you get are linking errors, because you did not specify `-lvncserver` when invoking gcc.

I guess the above could is incorrectly copied from `examples/simple.c`. You can compile it using `gcc simple.c -lvncserver -o simple`

Those are general C programming errors, nothing specific to libvncserver. So again, please make yourself familiar with compiling and linking C programs, before asking here again.

This could be good starting points:

http://pages.cs.wisc.edu/~beechung/ref/gcc-intro.html
https://www3.ntu.edu.sg/home/ehchua/programming/cpp/gcc_make.html

Greetings

**Comment by andrey-sitsko** [comment]
Thanks a lot for your help, I'am an totally amateur in linux(
