### ISSUE TITLE
How to set up libvncserver and UltraVNC-Repeater?

### ISSUE THREAD

**Issue by schlegea** [LibVNC/libvncserver#87]
Hi,

I’m implementing an remote support solution with libvncserver on embedded devices and I want to use UltraVNC-Repeater to tunnel the NAT of our customers. I use the libvncserver library within a program written in C.

The server works and I also use the code of the libvncserver sample ‘repeater’ to connect to the repeater with an ID.

I can connect to the vnc server over the IP-Address shown in the log and at the moment over DNS ( because server and client are currently in the same IP range). 

But how can I connect to the server ID directly instead of the IP?

Can someone tell me how to set up the server to connect over ID to the repeater and how can I connect to this ID with UltraVNC viewer?

Thanks a lot
Andreas

**Comment by antenore** [comment]
1. The VN client connects to the repeater  
  
```
server: ID:100000  
repeater: IP of the repeater:5901 (default port for repeaters)  
```
  
2. The server connects to the repeater on port 5500 (VNC server that become a client to the repeater).

The repeater then matches both IDs and internally route the connection to the correct server/client. The goal of the repeater is to avoid having setting up firewalls and NAT rules, since all connections become outbound.

**Comment by antenore** [comment]
So you cannot really avoid the IP, because the client needs to know where the repeater is.

Can you please detail which part of the documentation should be improved?

**Comment by bk138** [comment]
The process is very nicely described in https://github.com/LibVNC/libvncserver/issues/465#issuecomment-1026279816 - will add this to the official documentation
